### ISSUE TITLE
Uppercase in interestOverTime

### ISSUE THREAD

**Issue by hadrienadmo** [x-fran/g-trends#10]
Hello everyone,

I am getting a 400 Bad Request when trying to use **interestOverTime**.

```
$gt = new GTrends();
$trends = $gt->interestOverTime('github', 0, 'today 3-m');
```

It seems to be caused by the period (time) whose value _$timeUnit_ is set to uppercase which lead to the bad request error.

Changing the line 341:
`$timeInfo[] = strtoupper($timeUnit);`
by this one:
`$timeInfo[] = $timeUnit;`
fix the problem.

Am I the only one having this issue ?

**Comment by x-fran** [comment]
Hi @hadrienadmo,

That was a bug. Fixed now.
Thank you for reporting

**Comment by x-fran** [comment]
Hi @hadrienadmo,

That was a bug. Fixed now.
Thank you for reporting

**Comment by hadrienadmo** [comment]
Hello @x-fran,

Thank you for the fix (and also for this API)  :+1:
