### ISSUE TITLE
interestOverTime() Method does not return any data

### ISSUE THREAD

**Issue by hakkikonu** [x-fran/g-trends#14]
I tried many keywords but it returns noting.

Test: 

```
print_r("\n\n <h1>GTrends interestOverTime</h1>\n ");
print_r($gt->interestOverTime('Taylor Swift'));
print_r("\n\n");
```
Returns :
null

Expected:
interestOverTime Array with related data.

@x-fran

**Comment by BobSmithJoe** [comment]
Same for me. Any idea what is going on?

**Comment by x-fran** [comment]
I will try to take a look as soon as I can. Meanwhile, any push request is more than welcome.

**Comment by x-fran** [comment]
Works for me.

```
GTrends interestOverTime

 Array
(
    [0] => Array
        (
            [time] => 1562886900
            [formattedTime] => Jul 12, 2019 at 12:15 AM
            [formattedAxisTime] => 12:15 AM
            [value] => Array
                (
                    [0] => 0
                )

            [hasData] => Array
                (
                    [0] => 
                )

            [formattedValue] => Array
                (
                    [0] => 0
                )

        )
.............
.............
```

Please make sure the parameters you're using are good.

**Comment by Daddaniele** [comment]
HI, 
trying to call interestOverTime(), 

`var_dump($gt->interestOverTime('Donald Trump'))`

i get
bool(false)

gtrends installed via composer ( today ) with
`$ composer require x-fran/g-trends`

php7.something

Could you please kindly provide your working string ?
also tried 
`var_dump($gt->interestOverTime(['Donald Trump'[))`
same result
