### ISSUE TITLE
Parse error: syntax error, unexpected '?' in g-trends-master/src/Google/GTrends.php on line 147

### ISSUE THREAD

**Issue by Sukhpall-Singh** [x-fran/g-trends#27]
I am trying to integrate this on my site but I am facing above problem when i am implementing on server. I tested it on local system and its working fine but I dont know why it is not working on server. Here is the line in GTrends.php where it is showing error:
 

> $kWord = $widget['request']['restriction']['complexKeywordsRestriction']['keyword'][0]['value'] ?? null;

Is there any php version problem? because in my local system I have installed php version 7.1.2 but on server its 5.6.2?
 Thanks!

**Comment by x-fran** [comment]
The recommended PHP version is 7 and up.
