### ISSUE TITLE
 Why is the return value empty after I changed the time parameter？

### ISSUE THREAD

**Issue by jzd16boof** [x-fran/g-trends#30]
Hello, when I use the getRelatedSearchQueries method, as soon as I change the time, the return is empty. I read the GTrends.php file. The default time of the getRelatedSearchQueries method is today 12-m. Why as long as this time is modified, the return is empty.

**Comment by rbnfsh** [comment]
for me anything above 12-m i.e. 24-m or 2-y returns empty

**Comment by jzd16boof** [comment]
> for me anything above 12-m i.e. 24-m or 2-y returns empty

I found a way to return the data correctly. Don’t use time like ‘today 12-m’ in this format, just use a time format like “2020-06-01 2020-06-21”.

**Comment by rbnfsh** [comment]
Thanks this worked
