### ISSUE TITLE
When geo is worldwide, relatedQueries doesn't work

### ISSUE THREAD

**Issue by hbluestar27** [x-fran/g-trends#31]
$options = [
        'hl'  => 'en-US',
        'tz'  => -60, # last hour
        'geo' => '',
    ];
// geo is worldwide

If I set the option as above, relatedQueries does not work.
Who can give me a solution for worldwide relatedQueries?

**Comment by x-fran** [comment]
Fixed c15eaf56577f8bd940387bd4012b26b675710299
