### ISSUE TITLE
time

### ISSUE THREAD

**Issue by shahreahang** [x-fran/g-trends#32]
Hello,

How can I set new time , for example now 1-H in my query ?
I set 'time'  => 'now 1-H', in $options and its not working.
I looked into GTrends.php line 192 and I found $time='today 12-m'
should I change time from here ??

**Comment by x-fran** [comment]
You have to pass the time as parameter in the function you're using not in the options like this:
`$gt->interestOverTime('Donald Trump', 0, 'now 1-H')`
