### ISSUE TITLE
Information / documentation for getRealTimeSearchTrends() ?

### ISSUE THREAD

**Issue by pressreset** [x-fran/g-trends#33]
Hi,

I don't see any information for getRealTimeSearchTrends() which was merged in pull
https://github.com/x-fran/g-trends/commit/77357f2c8db83573b70b2d0fb20e71d97220e1d1
?

/**
		* @param string $cat
		* @param int $fi
		* @param int $fs
		* @param int $ri
		* @param int $rs
		* @param int $sort
		* @return mixed
		*/

Is extremely obtuse and I don't know what fi,fs,ri,rs are or how the sort works? I've looked through the docs for pyTrends too which some of this is based on but I don't even see anything?

Also, a good thing to add to the documentation is:
use Google\GTrends;

I can create a bunch of pull requests, and will gladly add/update the documentation if I can get more information on what/how exactly getRealTimeSearchTrends is working.

**Comment by pressreset** [comment]
I figured categories out, but I still have no idea what the others are.
You need to apply the category not as the standard category identifier string-int or category name from the "Categories", but as a single letter str:

all: default
b: business
e: entertainment
m: health/medical
t: sci/tech
s: sports
h: top stories

**Comment by x-fran** [comment]
Thank you for your updates @pressreset
