### ISSUE TITLE
Death of app by JSON's "Decoding failed: Syntax error" by exception

### ISSUE THREAD

**Issue by DrLightman** [x-fran/g-trends#36]
For example in `::getDailySearchTrends`

```php
/**
 * @param int $ns
 * @return mixed
 */
public function getDailySearchTrends($ns=15)
{
    $params =[
        'hl'    => $this->options['hl'],
        'tz'    => $this->options['tz'],
        'geo'   => $this->options['geo'],
        'ns'    => $ns,
    ];

    try {

        $dataJson = $this->_getData(self::DAILY_SEARCH_TRENDS_ENDPOINT, 'GET', $params);
        return Json\Json::decode(trim(substr($dataJson, 5)), Json\Json::TYPE_ARRAY);
    } catch (\Exception $e) {

        die($e->getMessage());
    }
}
```

Isn't this too much? I would be fine to handle the false and provide the user with some sort of UI message saying there is something wrong with the server or other.

**Comment by ryankaka92** [comment]
Hi
Can you take a look at my problem?
https://github.com/x-fran/g-trends/issues/37

**Comment by x-fran** [comment]
The function is returning an array or false if no results. If an exception is raised, then there is a bug an needs to be fixed.
Just tested `getDailySearchTrends` and works as expected.
