### ISSUE TITLE
Call to undefined method Google\GTrends::relatedQueries

### ISSUE THREAD

**Issue by ryankaka92** [x-fran/g-trends#37]
```
<?php 


include __DIR__.'/vendor/autoload.php';

use Google\GTrends;

# This options are by default if none provided
$options = [
		'hl'  => 'en-US',
		'tz'  => -60, # last hour
		'geo' => 'IE',
	];
$gt = new GTrends($options);


print_r( $gt->relatedQueries(['games']));
```

Hey guys did I make a mistake? I installed with composer;

It gives this error:
`PHP Fatal error:  Uncaught Error: Call to undefined method Google\GTrends::relatedQueries() in /root/gtrends/get.php:17
Stack trace:
#0 {main}
  thrown in /root/gtrends/get.php on line 17`

**Comment by DrLightman** [comment]
Where did you get the "relatedQueries()" method?

You can see a list of supported methods in this file:

`\vendor\x-fran\g-trends\index.php`

**Comment by ryankaka92** [comment]
Hello
I got it here:

https://github.com/x-fran/g-trends#related-queries

**Comment by ryankaka92** [comment]
It seems like its getRelatedSearchQueries not relatedQueries
please fix it on the homepage.


```
# This options are by default if none provided
$options = [
		'hl'  => 'en-US',
		'tz'  => -240, # last hour
		'geo' => 'US',
	];
$gt = new GTrends($options);
```


Also if I may ask
Is this the correct way to get the data for last 4 hours?
` $gt->getRelatedSearchQueries(['games']);`

Thank you veey much for responding.

**Comment by x-fran** [comment]
Just pushed a fix for getRelatedSearchQueries.
Here an example for one hour: `gt->getRelatedSearchQueries(['Donald Trump'], 0, 'now 4-H') `
