### ISSUE TITLE
api down ? 

### ISSUE THREAD

**Issue by ckdapps** [x-fran/g-trends#38]
hi

great job there. Was working like a charm for the last 2 days and suddently it shows nothing, no error message or anything to help me debug. I'm using the interestOverTime query. 

the output is just fully empty. 

here is my code : 

use Google\GTrends;

    # This options are by default if none provided
    $options = [
        'hl'  => 'fr-FR',
        'tz'  => 0, # last hour
        'geo' => '',
    ];
$gt = new GTrends($options);
$gtrend = $gt->interestOverTime('bitcoin', 0 , 'now 1-d');

print_r($gtrend);

as an extra peace of info, when i call the demo page, there is also nnothing in the section interestOverTime

any clue ?

**Comment by x-fran** [comment]
Sorry. I cannot reproduce.
