### ISSUE TITLE
Trends API no longer works

### ISSUE THREAD

**Issue by richyray92** [x-fran/g-trends#4]
It seems Google has changed the endpoints?

**Comment by genericox** [comment]
No. But for now you have to save the cookie session to proceed request. I am working on it and if I can get something working, I'll make a pull request.

**Comment by genericox** [comment]
I have now a workaround, changing the file Curl.php (..vendor\zendframework\zend-http\src\Client\Adapter\Curl.php)

where you find: 

`$response = curl_exec($this->curl);`

change for:

`        $cookie_jar = tempnam('/tmp','cookie');
        curl_setopt($this->curl, CURLOPT_COOKIEJAR, $cookie_jar);

        $response = curl_exec($this->curl);
       
        curl_setopt($this->curl, CURLOPT_COOKIEFILE, $cookie_jar);

        $response = curl_exec($this->curl);
        unlink($cookie_jar);`

**Comment by richyray92** [comment]
I have verified it works. Thanks!

**Comment by x-fran** [comment]
@richyray92 Thanks for reporting.
Issue fiixed in the last commit [5f19dac](https://github.com/x-fran/g-trends/commit/ab6bcfabb05f9bb97e3953e7eff43ca22cf89289)

@genericox Not good practice modify vendors libraries.
