### ISSUE TITLE
PHP 8.0 support 

### ISSUE THREAD

**Issue by simaodiascosta** [x-fran/g-trends#40]
Hey,

Can you add support to PHP 8.0 in composer.json:31?

From:     
>     "php" : "^7.0",
To:
>     "php" : "^7.0|^8.0",

Not considering any possible implications in code with this upgrade.

Cheers

**Comment by simaodiascosta** [comment]
Great! Thanks for your time

**Comment by bastienu** [comment]
I made a PR on this.
