### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by sfatfarma** [x-fran/g-trends#9]
Hello,

Great code, congrats!

Starting recently, I am unable to use the script, I get each time a 404 return code for https://trends.google.com/trends/hottrends/hotItems

Does this mean that the Google Trends endpoint is no longer available and that this library is dead? :(

Regards,
Szabi.

**Comment by x-fran** [comment]
Soon I will release a new, improved and debugged version.
Thank you.

**Comment by x-fran** [comment]
Google changed some endpoints. 
https://trends.google.com/trends/hottrends/hotItems is no longer available.

**Comment by sfatfarma** [comment]
Thank you very much for the update.
